kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: logistics-team
  name: lg-team
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["pods", "services", "deployments", "endpoints", "replicasets", "configmaps", "statefulsets", "daemonsets", "jobs", "cronjobs", "configmaps", "ingresses", "persistentvolumes", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]