kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lg-team
  namespace: logistics-team
subjects:
- kind: ServiceAccount
  name: lg-team
  namespace: logistics-team
roleRef:
  kind: Role
  name: lg-team
  apiGroup: rbac.authorization.k8s.io