apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metabase
  namespace: metabase
spec:
  rules:
  - host: metabase-operations.digikala.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: metabase
            port:
              number: 80
